# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5d66d0a258f18a87f14bf2b85c58eca52ef583d4059c93bd22d91efdae80ad1a78b1fec035dcf221645205e0e3cd5e1268830303c8199340ac5ec038f54d2c

test:
  secret_key_base: a5a34a4aae0ee2e602a88e6379af277ac1db4cbb9079d499bbb74b1f2d96496e054eed3c4373e0573537dd5dc186d707a4006827f0929c48473e51959fe523f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
